# -------------------------------------------------------------------------
# Per-spack-instance settings (overrides defaults):
#   $SPACK_ROOT/etc/spack/modules.yaml
#
# Per-user settings (overrides default and site settings):
#   ~/.spack/modules.yaml
# -------------------------------------------------------------------------
modules:
  tcl: 
     whitelist: 
       - 'gcc%gcc' 
       - 'geant4' 
       - 'root' 
       - 'parallel' 
       - 'boost%intel' 
       - 'jdk' 
       - 'r%intel' 
       - 'python%intel' 
       - 'perl%intel' 
       - 'singularity' 
       - 'ffmpeg' 
       - 'paraview' 
       - 'jmol' 
       - 'openbabel' 
       - 'gromacs' 
       - 'lammps' 
       - 'nwchem' 
     blacklist: 
       - '%gcc' 
       - '%intel' 
     hash_length: 0 
     naming_scheme: '${PACKAGE}/${VERSION}' 
     all: 
       conflict: 
         - '${PACKAGE}' 
       suffixes: 
         '^mkl': mkl 
         '^openblas': openblas 
         '^netlib-lapack': netlib 
         '^openmpi': openmpi 
         '^mpich': mpich 
     ^r: 
        autoload: 'all' 

  enable:
    - tcl
    - dotkit
  prefix_inspections:
    bin:
      - PATH
    man:
      - MANPATH
    share/man:
      - MANPATH
    share/aclocal:
      - ACLOCAL_PATH
    lib:
      - LIBRARY_PATH
      - LD_LIBRARY_PATH
    lib64:
      - LIBRARY_PATH
      - LD_LIBRARY_PATH
    include:
      - CPATH
    lib/pkgconfig:
      - PKG_CONFIG_PATH
    lib64/pkgconfig:
      - PKG_CONFIG_PATH
    '':
      - CMAKE_PREFIX_PATH

  lmod:
    hierarchy:
      - mpi
