#!/bin/bash

# need at least 1 arg
if [ -z $1 ]; then
	echo
	echo "Creates a new ZFS filesystem called storage/home/<username> with mountpoint /home/<domain name>/<username>"
	echo
	echo "You must supply a username and (optionally) a domain name."
	echo "If no domain name is supplied, usd.local is assumed."
	echo "Usage:"
	echo -e "\t $0 <username> [domain name]"
	echo "EXAMPLES:"
	echo -e "\t $0 bjohnson"
	echo -e "\t $0 jsmith jacks.local"
	echo
	exit 1
fi

USERNAME=$1
DOMAIN="usd.local"
if [ ! -z $2 ]; then
	DOMAIN="$2"
fi

uid=$(/bin/id -u $USERNAME)
GID="1093600513" # "domain users@usd.local"

echo "Setting up user $USERNAME with uid $uid"

STORAGE_HOST="zfs01"
FILESYSTEM="storage/home/$USERNAME"
MOUNTPOINT="/storage/home/$DOMAIN/$USERNAME"
QUOTA="50GB"

ssh $STORAGE_HOST <<EOF
zfs create -o mountpoint=$MOUNTPOINT -o quota=$QUOTA $FILESYSTEM
chown $uid:$GID $MOUNTPOINT
chmod 700 $MOUNTPOINT
EOF

# Copy dotfiles
tar -C /etc/skel -cf - . | tar -C /home/$DOMAIN/$USERNAME -xf -
chown -R $uid:$GID /home/$DOMAIN/$USERNAME
chmod 700 /home/$DOMAIN/$USERNAME

echo "Done"
echo
echo "Now run:"
echo "su -l $USERNAME"

exit 0
