#!/bin/bash

# need at least 1 arg
if [ -z $1 ]; then
	echo
	echo "Creates a new ZFS filesystem called storage/home/<username> with mountpoint /home/<domain name>/<username>"
	echo
	echo "You must supply a username and (optionally) a domain name."
	echo "If no domain name is supplied, usd.local is assumed."
	echo "Usage:"
	echo -e "\t $0 <username> [domain name]"
	echo "EXAMPLES:"
	echo -e "\t $0 bjohnson"
	echo -e "\t $0 jsmith jacks.local"
	echo
	exit 1
fi

# check to make sure users don't do something like ./setup_homedir bill.conn@usd.local
# added by bill - 20190920
AT="@"
if [[ "$1" =~ "$AT" ]];
then
    echo "Make sure you don't include the @domain.local in the username"
    exit 1
fi


USERNAME=$1
DOMAIN="usd.local"
if [ ! -z $2 ]; then
	DOMAIN="$2"
fi

# We need to force lowercase usernames because admins forget when creating home directories
# and if you create a home directory with upper case letters, it doesn't get mapped correctly
# when the user logs in. - Added by bill - 20191202
USERNAME=$(echo $USERNAME | awk '{print tolower($0)}')

uid=$(/bin/id -u "$USERNAME"@"$DOMAIN")
GID="1093600513" # "domain users@usd.local"

echo "Setting up user $USERNAME with uid $uid"

STORAGE_HOST="zfs01"
FILESYSTEM="storage/home/$USERNAME"
MOUNTPOINT="/storage/home/$DOMAIN/$USERNAME"
QUOTA="50GB"

ssh $STORAGE_HOST <<EOF
zfs create -o mountpoint=$MOUNTPOINT -o quota=$QUOTA $FILESYSTEM
chown $uid:$GID $MOUNTPOINT
chmod 700 $MOUNTPOINT
EOF

# Copy dotfiles
tar -C /etc/skel -cf - . | tar -C /home/$DOMAIN/$USERNAME -xf -
chown -R $uid:$GID /home/$DOMAIN/$USERNAME
chmod 700 /home/$DOMAIN/$USERNAME

echo "Done"
echo
echo "Now run:"
echo "su -l $USERNAME"

exit 0
