# -------------------------------------------------------------------------
# Per-spack-instance settings (overrides defaults):
#   $SPACK_ROOT/etc/spack/packages.yaml
#
# Per-user settings (overrides default and site settings):
#   ~/.spack/packages.yaml
# -------------------------------------------------------------------------
packages:
  all:
    compiler: [intel@17.0.4, gcc@4.8.5, pgi]
    providers:
      awk: [gawk]
      blas: [intel-mkl]
      daal: [intel-daal]
      elf: [elfutils]
      golang: [gcc]
      ipp: [intel-ipp]
      java: [jdk]
      lapack: [intel-mkl]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [openmpi, mpich]
      opencl: [pocl]
      openfoam: [openfoam-com, openfoam-org, foam-extend]
      pil: [py-pillow]
      scalapack: [intel-mkl]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      jpeg: [libjpeg-turbo, libjpeg]
  freebayes:
    compiler: [gcc]
  fastx-toolkit:
    compiler: [gcc]
  bowtie:
    compiler: [gcc]
  geant4:
    compiler: [gcc@6.3.0]
    variants: -qt
  root:
    compiler: [gcc@6.3.0]
  intel-mkl:
    buildable: False
    paths:
      intel-mkl@17.0.4%intel@17.0.4 arch=linux-x86_64: /opt/intel
